
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Aug  4 2024 07:10:00

// Verification Directory fv/asynchronous_fifo 

module fifo_mem(wclk, w_en, rclk, r_en, waddr, raddr, wdata, full,
     empty, rdata);
  input wclk, w_en, rclk, r_en, full, empty;
  input [9:0] waddr, raddr;
  input [7:0] wdata;
  output [7:0] rdata;
  wire wclk, w_en, rclk, r_en, full, empty;
  wire [9:0] waddr, raddr;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  sky130_sram_1kbyte_1rw1r_8x1024_8 RAM(.din0 (wdata), .addr0
       ({5'b00000, waddr[4:0]}), .wmask0 (w_en), .csb0 (full), .web0
       (1'b0), .clk0 (wclk), .addr1 ({5'b00000, raddr[4:0]}), .csb1
       (r_en), .clk1 (rclk), .dout0 ({UNCONNECTED6, UNCONNECTED5,
       UNCONNECTED4, UNCONNECTED3, UNCONNECTED2, UNCONNECTED1,
       UNCONNECTED0, UNCONNECTED}), .dout1 (rdata));
endmodule

module rptr_handler_PTR_WIDTH10(rclk, rrst_n, r_en, g_wptr_sync,
     b_rptr, g_rptr, empty);
  input rclk, rrst_n, r_en;
  input [10:0] g_wptr_sync;
  output [10:0] b_rptr, g_rptr;
  output empty;
  wire rclk, rrst_n, r_en;
  wire [10:0] g_wptr_sync;
  wire [10:0] b_rptr, g_rptr;
  wire empty;
  wire [10:0] g_rptr_next;
  wire [10:0] b_rptr_next;
  wire adder_n_37, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_62, n_63, n_64, n_88, n_143, n_176, n_178;
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[3] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[3]), .Q (g_rptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[1] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[1]), .Q (g_rptr[1]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[2] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[2]), .Q (g_rptr[2]));
  sky130_fd_sc_hd__xor2_1 g324(.A (n_176), .B (b_rptr_next[4]), .X
       (g_rptr_next[3]));
  sky130_fd_sc_hd__xor2_1 g325(.A (b_rptr_next[3]), .B
       (b_rptr_next[2]), .X (g_rptr_next[2]));
  sky130_fd_sc_hd__o21ai_1 g326(.A1 (n_25), .A2 (b_rptr_next[2]), .B1
       (n_29), .Y (g_rptr_next[1]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[0] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[0]), .Q (g_rptr[0]));
  sky130_fd_sc_hd__nand2_1 g328(.A (b_rptr_next[2]), .B (n_25), .Y
       (n_29));
  sky130_fd_sc_hd__o21ai_2 g329(.A1 (b_rptr[4]), .A2 (n_24), .B1
       (n_28), .Y (b_rptr_next[4]));
  sky130_fd_sc_hd__nand2_1 g330(.A (n_24), .B (b_rptr[4]), .Y (n_28));
  sky130_fd_sc_hd__o21ai_1 g331(.A1 (b_rptr_next[0]), .A2 (n_25), .B1
       (n_26), .Y (g_rptr_next[0]));
  sky130_fd_sc_hd__a21o_1 g332(.A1 (n_22), .A2 (n_63), .B1 (n_27), .X
       (b_rptr_next[2]));
  sky130_fd_sc_hd__nor2_1 g333(.A (n_63), .B (n_22), .Y (n_27));
  sky130_fd_sc_hd__nand2_1 g334(.A (n_25), .B (b_rptr_next[0]), .Y
       (n_26));
  sky130_fd_sc_hd__inv_2 g335(.A (b_rptr_next[1]), .Y (n_25));
  sky130_fd_sc_hd__o21ai_1 g336(.A1 (n_62), .A2 (n_21), .B1 (n_23), .Y
       (b_rptr_next[3]));
  sky130_fd_sc_hd__nand2_1 g337(.A (n_21), .B (n_62), .Y (n_23));
  sky130_fd_sc_hd__nand2_1 g338(.A (n_20), .B (b_rptr[3]), .Y (n_24));
  sky130_fd_sc_hd__o2bb2ai_1 g339(.A1_N (n_18), .A2_N (n_16), .B1
       (n_18), .B2 (n_16), .Y (b_rptr_next[0]));
  sky130_fd_sc_hd__o2bb2ai_1 g340(.A1_N (n_64), .A2_N (n_19), .B1
       (b_rptr[1]), .B2 (n_19), .Y (b_rptr_next[1]));
  sky130_fd_sc_hd__nand3_1 g341(.A (r_en), .B (n_15), .C (n_64), .Y
       (n_22));
  sky130_fd_sc_hd__inv_1 g342(.A (n_21), .Y (n_20));
  sky130_fd_sc_hd__nand2_2 g343(.A (r_en), .B (n_17), .Y (n_21));
  sky130_fd_sc_hd__nand2_1 g344(.A (r_en), .B (n_15), .Y (n_19));
  sky130_fd_sc_hd__and3_2 g345(.A (n_15), .B (n_63), .C (n_64), .X
       (n_17));
  sky130_fd_sc_hd__xor2_1 g346(.A (adder_n_37), .B (n_30), .X (n_18));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[10] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[10]), .Q (g_rptr[10]));
  sky130_fd_sc_hd__nand2b_1 g348(.A_N (empty), .B (r_en), .Y (n_16));
  sky130_fd_sc_hd__nor2b_1 g349(.A (empty), .B_N (n_30), .Y (n_15));
  sky130_fd_sc_hd__dfstp_2 empty_reg(.SET_B (rrst_n), .CLK (rclk), .D
       (n_14), .Q (empty));
  sky130_fd_sc_hd__nor3_2 g219(.A (n_9), .B (n_8), .C (n_13), .Y
       (n_14));
  sky130_fd_sc_hd__nand4_1 g220(.A (n_6), .B (n_4), .C (n_5), .D
       (n_12), .Y (n_13));
  sky130_fd_sc_hd__a21oi_1 g221(.A1 (g_rptr_next[3]), .A2 (n_1), .B1
       (n_11), .Y (n_12));
  sky130_fd_sc_hd__o221ai_1 g222(.A1 (n_0), .A2 (b_rptr_next[4]), .B1
       (g_wptr_sync[4]), .B2 (n_2), .C1 (n_10), .Y (n_11));
  sky130_fd_sc_hd__a21oi_1 g223(.A1 (g_wptr_sync[9]), .A2 (n_3), .B1
       (n_7), .Y (n_10));
  sky130_fd_sc_hd__a2bb2oi_1 g224(.A1_N (g_wptr_sync[0]), .A2_N
       (g_rptr_next[0]), .B1 (g_wptr_sync[0]), .B2 (g_rptr_next[0]), .Y
       (n_9));
  sky130_fd_sc_hd__a2bb2oi_1 g225(.A1_N (g_wptr_sync[1]), .A2_N
       (g_rptr_next[1]), .B1 (g_wptr_sync[1]), .B2 (g_rptr_next[1]), .Y
       (n_8));
  sky130_fd_sc_hd__mux2i_1 g226(.A0 (n_3), .A1 (g_wptr_sync[9]), .S
       (g_wptr_sync[10]), .Y (n_7));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[4] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[4]), .Q (b_rptr[4]));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[0] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[0]), .Q (n_30));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[3] (.RESET_B (rrst_n), .CLK
       (rclk), .D (n_176), .Q (n_62));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[1] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[1]), .Q (n_64));
  sky130_fd_sc_hd__nand2b_1 g231(.A_N (g_rptr_next[3]), .B
       (g_wptr_sync[3]), .Y (n_6));
  sky130_fd_sc_hd__nand2b_1 g232(.A_N (g_wptr_sync[2]), .B
       (g_rptr_next[2]), .Y (n_5));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[2] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[2]), .Q (n_63));
  sky130_fd_sc_hd__nand2b_1 g234(.A_N (g_rptr_next[2]), .B
       (g_wptr_sync[2]), .Y (n_4));
  sky130_fd_sc_hd__inv_1 g235(.A (b_rptr_next[10]), .Y (n_3));
  sky130_fd_sc_hd__clkinv_1 g236(.A (b_rptr_next[4]), .Y (n_2));
  sky130_fd_sc_hd__inv_1 g237(.A (g_wptr_sync[3]), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g238(.A (g_wptr_sync[4]), .Y (n_0));
  sky130_fd_sc_hd__clkinv_2 drc_bufs368(.A (n_88), .Y (b_rptr[0]));
  sky130_fd_sc_hd__inv_1 drc_bufs369(.A (n_30), .Y (n_88));
  sky130_fd_sc_hd__clkinv_2 drc_bufs414(.A (n_143), .Y (b_rptr[2]));
  sky130_fd_sc_hd__inv_1 drc_bufs415(.A (n_63), .Y (n_143));
  sky130_fd_sc_hd__buf_6 drc427(.A (n_64), .X (b_rptr[1]));
  sky130_fd_sc_hd__buf_6 drc439(.A (n_62), .X (b_rptr[3]));
  sky130_fd_sc_hd__clkinv_1 drc_bufs(.A (n_178), .Y (n_176));
  sky130_fd_sc_hd__inv_1 drc_bufs445(.A (b_rptr_next[3]), .Y (n_178));
endmodule

module synchronizer_WIDTH10_1(clk, rst_n, d_in, d_out);
  input clk, rst_n;
  input [10:0] d_in;
  output [10:0] d_out;
  wire clk, rst_n;
  wire [10:0] d_in;
  wire [10:0] d_out;
  wire [10:0] q1;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_44;
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[2] (.CLK (clk), .D (n_9), .Q
       (d_out[2]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[1] (.CLK (clk), .D (n_10), .Q
       (d_out[1]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[10] (.CLK (clk), .D (n_11), .Q
       (d_out[10]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[9] (.CLK (clk), .D (n_12), .Q
       (d_out[9]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[3] (.CLK (clk), .D (n_8), .Q
       (d_out[3]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[0] (.CLK (clk), .D (n_13), .Q
       (d_out[0]));
  sky130_fd_sc_hd__and2_0 g26(.A (q1[0]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__and2_0 g25(.A (q1[9]), .B (rst_n), .X (n_12));
  sky130_fd_sc_hd__and2_0 g27(.A (q1[10]), .B (rst_n), .X (n_11));
  sky130_fd_sc_hd__and2_0 g28(.A (q1[1]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__and2_0 g29(.A (q1[2]), .B (rst_n), .X (n_9));
  sky130_fd_sc_hd__and2_0 g30(.A (q1[3]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[9] (.CLK (clk), .D (n_44), .Q
       (q1[9]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[10] (.CLK (clk), .D (n_44), .Q
       (q1[10]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[2] (.CLK (clk), .D (n_5), .Q
       (q1[2]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[1] (.CLK (clk), .D (n_2), .Q
       (q1[1]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[3] (.CLK (clk), .D (n_7), .Q
       (q1[3]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[0] (.CLK (clk), .D (n_4), .Q
       (q1[0]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[4] (.CLK (clk), .D (n_1), .Q
       (d_out[4]));
  sky130_fd_sc_hd__and2_0 g44(.A (d_in[3]), .B (rst_n), .X (n_7));
  sky130_fd_sc_hd__and2_0 g40(.A (d_in[2]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__and2_0 g41(.A (d_in[0]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__and2_0 g43(.A (d_in[1]), .B (rst_n), .X (n_2));
  sky130_fd_sc_hd__and2_0 g31(.A (q1[4]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[4] (.CLK (clk), .D (n_0), .Q
       (q1[4]));
  sky130_fd_sc_hd__and2_1 g45(.A (d_in[4]), .B (rst_n), .X (n_0));
  sky130_fd_sc_hd__and2_1 g60(.A (d_in[9]), .B (rst_n), .X (n_44));
endmodule

module synchronizer_WIDTH10(clk, rst_n, d_in, d_out);
  input clk, rst_n;
  input [10:0] d_in;
  output [10:0] d_out;
  wire clk, rst_n;
  wire [10:0] d_in;
  wire [10:0] d_out;
  wire [10:0] q1;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_44;
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[0] (.CLK (clk), .D (n_8), .Q
       (d_out[0]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[9] (.CLK (clk), .D (n_9), .Q
       (d_out[9]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[3] (.CLK (clk), .D (n_10), .Q
       (d_out[3]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[2] (.CLK (clk), .D (n_11), .Q
       (d_out[2]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[1] (.CLK (clk), .D (n_12), .Q
       (d_out[1]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[10] (.CLK (clk), .D (n_13), .Q
       (d_out[10]));
  sky130_fd_sc_hd__and2_0 g25(.A (q1[10]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__and2_0 g26(.A (q1[1]), .B (rst_n), .X (n_12));
  sky130_fd_sc_hd__and2_0 g27(.A (q1[2]), .B (rst_n), .X (n_11));
  sky130_fd_sc_hd__and2_0 g28(.A (q1[3]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__and2_0 g30(.A (q1[9]), .B (rst_n), .X (n_9));
  sky130_fd_sc_hd__and2_0 g31(.A (q1[0]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[1] (.CLK (clk), .D (n_5), .Q
       (q1[1]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[2] (.CLK (clk), .D (n_4), .Q
       (q1[2]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[3] (.CLK (clk), .D (n_7), .Q
       (q1[3]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[9] (.CLK (clk), .D (n_44), .Q
       (q1[9]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[0] (.CLK (clk), .D (n_2), .Q
       (q1[0]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[10] (.CLK (clk), .D (n_44), .Q
       (q1[10]));
  sky130_fd_sc_hd__and2_1 g45(.A (d_in[3]), .B (rst_n), .X (n_7));
  sky130_fd_sc_hd__and2_1 g40(.A (d_in[1]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__and2_1 g41(.A (d_in[2]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__and2_1 g44(.A (d_in[0]), .B (rst_n), .X (n_2));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[4] (.CLK (clk), .D (n_1), .Q
       (d_out[4]));
  sky130_fd_sc_hd__and2_0 g29(.A (q1[4]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[4] (.CLK (clk), .D (n_0), .Q
       (q1[4]));
  sky130_fd_sc_hd__and2_1 g42(.A (d_in[4]), .B (rst_n), .X (n_0));
  sky130_fd_sc_hd__and2_1 g60(.A (d_in[9]), .B (rst_n), .X (n_44));
endmodule

module wptr_handler_PTR_WIDTH10(wclk, wrst_n, w_en, g_rptr_sync,
     b_wptr, g_wptr, full);
  input wclk, wrst_n, w_en;
  input [10:0] g_rptr_sync;
  output [10:0] b_wptr, g_wptr;
  output full;
  wire wclk, wrst_n, w_en;
  wire [10:0] g_rptr_sync;
  wire [10:0] b_wptr, g_wptr;
  wire full;
  wire [10:0] g_wptr_next;
  wire [10:0] b_wptr_next;
  wire adder_n_37, n_0, n_1, n_2, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_24, n_25, n_26;
  wire n_28, n_29, n_61, n_62, n_63, n_68, n_84, n_146;
  wire n_151, n_178, n_181, n_183, n_184, n_185, n_186, n_187;
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[3] (.RESET_B (wrst_n), .CLK
       (wclk), .D (n_185), .Q (g_wptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[1] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[1]), .Q (g_wptr[1]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[2] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[2]), .Q (g_wptr[2]));
  sky130_fd_sc_hd__xor2_1 g330(.A (n_68), .B (b_wptr_next[2]), .X
       (g_wptr_next[2]));
  sky130_fd_sc_hd__o21ai_1 g331(.A1 (n_24), .A2 (b_wptr_next[2]), .B1
       (n_28), .Y (g_wptr_next[1]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[0] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[0]), .Q (g_wptr[0]));
  sky130_fd_sc_hd__nand2_1 g333(.A (b_wptr_next[2]), .B (n_24), .Y
       (n_28));
  sky130_fd_sc_hd__o21ai_1 g336(.A1 (b_wptr_next[0]), .A2 (n_24), .B1
       (n_25), .Y (g_wptr_next[0]));
  sky130_fd_sc_hd__a21o_1 g337(.A1 (n_21), .A2 (n_62), .B1 (n_26), .X
       (b_wptr_next[2]));
  sky130_fd_sc_hd__nor2_1 g338(.A (n_62), .B (n_21), .Y (n_26));
  sky130_fd_sc_hd__nand2_1 g339(.A (n_24), .B (b_wptr_next[0]), .Y
       (n_25));
  sky130_fd_sc_hd__inv_2 g340(.A (b_wptr_next[1]), .Y (n_24));
  sky130_fd_sc_hd__o2bb2ai_1 g344(.A1_N (n_17), .A2_N (n_15), .B1
       (n_17), .B2 (n_15), .Y (b_wptr_next[0]));
  sky130_fd_sc_hd__o2bb2ai_1 g345(.A1_N (n_63), .A2_N (n_18), .B1
       (b_wptr[1]), .B2 (n_18), .Y (b_wptr_next[1]));
  sky130_fd_sc_hd__nand3_1 g346(.A (w_en), .B (n_14), .C (n_63), .Y
       (n_21));
  sky130_fd_sc_hd__inv_1 g347(.A (n_20), .Y (n_19));
  sky130_fd_sc_hd__nand2_1 g348(.A (w_en), .B (n_16), .Y (n_20));
  sky130_fd_sc_hd__nand2_1 g349(.A (w_en), .B (n_14), .Y (n_18));
  sky130_fd_sc_hd__and3_1 g350(.A (n_14), .B (n_62), .C (n_63), .X
       (n_16));
  sky130_fd_sc_hd__xor2_1 g351(.A (adder_n_37), .B (n_29), .X (n_17));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[10] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[10]), .Q (g_wptr[10]));
  sky130_fd_sc_hd__nand2b_1 g353(.A_N (full), .B (w_en), .Y (n_15));
  sky130_fd_sc_hd__nor2b_1 g354(.A (full), .B_N (n_29), .Y (n_14));
  sky130_fd_sc_hd__dfrtp_1 full_reg(.RESET_B (wrst_n), .CLK (wclk), .D
       (n_0), .Q (full));
  sky130_fd_sc_hd__nand4_1 g250(.A (n_6), .B (n_7), .C (n_5), .D
       (n_12), .Y (n_13));
  sky130_fd_sc_hd__a21oi_1 g251(.A1 (n_185), .A2 (n_2), .B1 (n_11), .Y
       (n_12));
  sky130_fd_sc_hd__o2111ai_1 g252(.A1 (b_wptr_next[10]), .A2
       (g_rptr_sync[10]), .B1 (n_8), .C1 (n_184), .D1 (n_183), .Y
       (n_11));
  sky130_fd_sc_hd__a2bb2oi_1 g253(.A1_N (g_rptr_sync[0]), .A2_N
       (g_wptr_next[0]), .B1 (g_rptr_sync[0]), .B2 (g_wptr_next[0]), .Y
       (n_10));
  sky130_fd_sc_hd__a2bb2oi_1 g254(.A1_N (g_rptr_sync[1]), .A2_N
       (g_wptr_next[1]), .B1 (g_rptr_sync[1]), .B2 (g_wptr_next[1]), .Y
       (n_9));
  sky130_fd_sc_hd__mux2i_1 g255(.A0 (g_rptr_sync[10]), .A1
       (b_wptr_next[10]), .S (g_rptr_sync[9]), .Y (n_8));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[4] (.RESET_B (wrst_n), .CLK
       (wclk), .D (n_187), .Q (b_wptr[4]));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[0] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[0]), .Q (n_29));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[3] (.RESET_B (wrst_n), .CLK
       (wclk), .D (n_68), .Q (n_61));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[1] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[1]), .Q (n_63));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[2] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[2]), .Q (n_62));
  sky130_fd_sc_hd__nand2b_1 g261(.A_N (g_wptr_next[2]), .B
       (g_rptr_sync[2]), .Y (n_7));
  sky130_fd_sc_hd__nand2b_1 g262(.A_N (n_185), .B (g_rptr_sync[3]), .Y
       (n_6));
  sky130_fd_sc_hd__nand2b_1 g263(.A_N (g_rptr_sync[2]), .B
       (g_wptr_next[2]), .Y (n_5));
  sky130_fd_sc_hd__inv_1 g266(.A (g_rptr_sync[3]), .Y (n_2));
  sky130_fd_sc_hd__nor2_1 g2(.A (n_1), .B (n_13), .Y (n_0));
  sky130_fd_sc_hd__or2_0 g3(.A (n_10), .B (n_9), .X (n_1));
  sky130_fd_sc_hd__clkinv_1 drc_bufs(.A (n_186), .Y (n_68));
  sky130_fd_sc_hd__clkinv_2 drc_bufs370(.A (n_84), .Y (b_wptr[0]));
  sky130_fd_sc_hd__inv_1 drc_bufs371(.A (n_29), .Y (n_84));
  sky130_fd_sc_hd__clkinv_2 drc_bufs423(.A (n_146), .Y (b_wptr[3]));
  sky130_fd_sc_hd__inv_1 drc_bufs424(.A (n_61), .Y (n_146));
  sky130_fd_sc_hd__clkinv_2 drc_bufs426(.A (n_151), .Y (b_wptr[2]));
  sky130_fd_sc_hd__inv_1 drc_bufs427(.A (n_62), .Y (n_151));
  sky130_fd_sc_hd__buf_6 drc439(.A (n_63), .X (b_wptr[1]));
  sky130_fd_sc_hd__nand2_1 g451(.A (n_19), .B (n_61), .Y (n_178));
  sky130_fd_sc_hd__nand2_1 g452(.A (n_178), .B (b_wptr[4]), .Y (n_181));
  sky130_fd_sc_hd__nand2b_1 g453(.A_N (n_187), .B (g_rptr_sync[4]), .Y
       (n_183));
  sky130_fd_sc_hd__nand2b_1 g454(.A_N (g_rptr_sync[4]), .B (n_187), .Y
       (n_184));
  sky130_fd_sc_hd__xor2_1 g455(.A (n_68), .B (n_187), .X (n_185));
  sky130_fd_sc_hd__xor2_1 g457(.A (n_61), .B (n_20), .X (n_186));
  sky130_fd_sc_hd__o21ai_2 g458(.A1 (b_wptr[4]), .A2 (n_178), .B1
       (n_181), .Y (n_187));
endmodule

module asynchronous_fifo(wclk, wrst_n, rclk, rrst_n, w_en, r_en,
     data_in, data_out, full, empty);
  input wclk, wrst_n, rclk, rrst_n, w_en, r_en;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty;
  wire wclk, wrst_n, rclk, rrst_n, w_en, r_en;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty;
  wire [10:0] b_wptr;
  wire [10:0] b_rptr;
  wire [10:0] g_wptr_sync;
  wire [10:0] g_rptr;
  wire [10:0] g_rptr_sync;
  wire [10:0] g_wptr;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0;
  wire UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8;
  wire UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z13,
       UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16;
  wire UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24;
  wire UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z27, n_35, n_37, n_41, n_43;
  fifo_mem fifom(wclk, w_en, rclk, r_en, {UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z, n_41, b_wptr[3:0]}, {UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z4, n_35, b_rptr[3:0]}, data_in, full,
       UNCONNECTED_HIER_Z9, data_out);
  rptr_handler_PTR_WIDTH10 rptr_h(rclk, rrst_n, r_en,
       {g_wptr_sync[10:9], UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, g_wptr_sync[4:0]},
       {b_rptr[10], UNCONNECTED11, UNCONNECTED10, UNCONNECTED9,
       UNCONNECTED8, UNCONNECTED7, b_rptr[4:0]}, {g_rptr[10],
       UNCONNECTED17, UNCONNECTED16, UNCONNECTED15, UNCONNECTED14,
       UNCONNECTED13, UNCONNECTED12, g_rptr[3:0]}, empty);
  synchronizer_WIDTH10_1 sync_rptr(wclk, wrst_n, {UNCONNECTED_HIER_Z18,
       g_rptr[10], UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z14, b_rptr[4],
       g_rptr[3:0]}, {g_rptr_sync[10:9], UNCONNECTED21, UNCONNECTED20,
       UNCONNECTED19, UNCONNECTED18, g_rptr_sync[4:0]});
  synchronizer_WIDTH10 sync_wptr(rclk, rrst_n, {UNCONNECTED_HIER_Z23,
       g_wptr[10], UNCONNECTED_HIER_Z22, UNCONNECTED_HIER_Z21,
       UNCONNECTED_HIER_Z20, UNCONNECTED_HIER_Z19, b_wptr[4],
       g_wptr[3:0]}, {g_wptr_sync[10:9], UNCONNECTED25, UNCONNECTED24,
       UNCONNECTED23, UNCONNECTED22, g_wptr_sync[4:0]});
  wptr_handler_PTR_WIDTH10 wptr_h(wclk, wrst_n, w_en,
       {g_rptr_sync[10:9], UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z24, g_rptr_sync[4:0]},
       {b_wptr[10], UNCONNECTED30, UNCONNECTED29, UNCONNECTED28,
       UNCONNECTED27, UNCONNECTED26, b_wptr[4:0]}, {g_wptr[10],
       UNCONNECTED36, UNCONNECTED35, UNCONNECTED34, UNCONNECTED33,
       UNCONNECTED32, UNCONNECTED31, g_wptr[3:0]}, full);
  sky130_fd_sc_hd__clkinv_2 drc_bufs(.A (n_37), .Y (n_35));
  sky130_fd_sc_hd__inv_1 drc_bufs6(.A (b_rptr[4]), .Y (n_37));
  sky130_fd_sc_hd__clkinv_2 drc_bufs10(.A (n_43), .Y (n_41));
  sky130_fd_sc_hd__inv_1 drc_bufs12(.A (b_wptr[4]), .Y (n_43));
endmodule

