
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Aug  5 2024 11:52:04

// Verification Directory fv/asynchronous_fifo 

module fifo_mem(wclk, w_en, rclk, r_en, waddr, raddr, wdata, full,
     empty, rdata);
  input wclk, w_en, rclk, r_en, full, empty;
  input [9:0] waddr, raddr;
  input [7:0] wdata;
  output [7:0] rdata;
  wire wclk, w_en, rclk, r_en, full, empty;
  wire [9:0] waddr, raddr;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  sky130_sram_1kbyte_1rw1r_8x1024_8 RAM(.din0 (wdata), .addr0
       ({5'b00000, waddr[4:0]}), .wmask0 (w_en), .csb0 (full), .web0
       (1'b0), .clk0 (wclk), .addr1 ({5'b00000, raddr[4:0]}), .csb1
       (r_en), .clk1 (rclk), .dout0 ({UNCONNECTED6, UNCONNECTED5,
       UNCONNECTED4, UNCONNECTED3, UNCONNECTED2, UNCONNECTED1,
       UNCONNECTED0, UNCONNECTED}), .dout1 (rdata));
endmodule

module rptr_handler_PTR_WIDTH10(rclk, rrst_n, r_en, g_wptr_sync,
     b_rptr, g_rptr, empty);
  input rclk, rrst_n, r_en;
  input [10:0] g_wptr_sync;
  output [10:0] b_rptr, g_rptr;
  output empty;
  wire rclk, rrst_n, r_en;
  wire [10:0] g_wptr_sync;
  wire [10:0] b_rptr, g_rptr;
  wire empty;
  wire [10:0] g_rptr_next;
  wire [10:0] b_rptr_next;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_71, n_72, n_73;
  assign g_rptr[4] = 1'b0;
  assign g_rptr[5] = 1'b0;
  assign g_rptr[6] = 1'b0;
  assign g_rptr[7] = 1'b0;
  assign g_rptr[8] = 1'b0;
  assign g_rptr[9] = 1'b0;
  assign b_rptr[5] = 1'b0;
  assign b_rptr[6] = 1'b0;
  assign b_rptr[7] = 1'b0;
  assign b_rptr[8] = 1'b0;
  assign b_rptr[9] = 1'b0;
  assign b_rptr[10] = 1'b0;
  sky130_fd_sc_hd__clkbuf_1 g51(.A (n_72), .X (b_rptr[1]));
  sky130_fd_sc_hd__clkbuf_1 g53(.A (n_73), .X (b_rptr[0]));
  sky130_fd_sc_hd__clkbuf_1 g52(.A (n_71), .X (b_rptr[2]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[3] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[3]), .Q (g_rptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[1] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[1]), .Q (g_rptr[1]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[2] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[2]), .Q (g_rptr[2]));
  sky130_fd_sc_hd__xor2_1 g463(.A (b_rptr_next[4]), .B
       (b_rptr_next[3]), .X (g_rptr_next[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[0] (.RESET_B (rrst_n), .CLK
       (rclk), .D (g_rptr_next[0]), .Q (g_rptr[0]));
  sky130_fd_sc_hd__xor2_1 g465(.A (b_rptr_next[2]), .B
       (b_rptr_next[3]), .X (g_rptr_next[2]));
  sky130_fd_sc_hd__xor2_1 g466(.A (b_rptr_next[2]), .B
       (b_rptr_next[1]), .X (g_rptr_next[1]));
  sky130_fd_sc_hd__o21ai_1 g467(.A1 (b_rptr[4]), .A2 (n_32), .B1
       (n_35), .Y (b_rptr_next[4]));
  sky130_fd_sc_hd__xor2_1 g468(.A (b_rptr_next[0]), .B
       (b_rptr_next[1]), .X (g_rptr_next[0]));
  sky130_fd_sc_hd__nand2_1 g469(.A (n_32), .B (b_rptr[4]), .Y (n_35));
  sky130_fd_sc_hd__nand2_1 g470(.A (n_33), .B (n_31), .Y
       (b_rptr_next[2]));
  sky130_fd_sc_hd__o21ai_2 g471(.A1 (b_rptr[3]), .A2 (n_30), .B1
       (n_34), .Y (b_rptr_next[3]));
  sky130_fd_sc_hd__nand2_1 g472(.A (n_30), .B (b_rptr[3]), .Y (n_34));
  sky130_fd_sc_hd__nand2_1 g473(.A (n_28), .B (n_71), .Y (n_33));
  sky130_fd_sc_hd__nand3b_1 g474(.A_N (n_71), .B (r_en), .C (n_25), .Y
       (n_31));
  sky130_fd_sc_hd__nand2_1 g475(.A (r_en), .B (n_29), .Y (n_32));
  sky130_fd_sc_hd__nand2_1 g476(.A (n_27), .B (n_26), .Y
       (b_rptr_next[1]));
  sky130_fd_sc_hd__and2_1 g477(.A (n_23), .B (b_rptr[3]), .X (n_29));
  sky130_fd_sc_hd__nand2_1 g478(.A (r_en), .B (n_25), .Y (n_28));
  sky130_fd_sc_hd__nand2_1 g479(.A (r_en), .B (n_23), .Y (n_30));
  sky130_fd_sc_hd__nand2_1 g480(.A (n_22), .B (n_72), .Y (n_27));
  sky130_fd_sc_hd__nand2_1 g481(.A (r_en), .B (n_24), .Y (n_26));
  sky130_fd_sc_hd__o2bb2ai_1 g482(.A1_N (n_73), .A2_N (n_20), .B1
       (n_73), .B2 (n_20), .Y (b_rptr_next[0]));
  sky130_fd_sc_hd__nor2_1 g483(.A (n_72), .B (n_19), .Y (n_24));
  sky130_fd_sc_hd__nor2_1 g484(.A (empty), .B (n_21), .Y (n_25));
  sky130_fd_sc_hd__nand2b_1 g485(.A_N (n_19), .B (r_en), .Y (n_22));
  sky130_fd_sc_hd__nor3_1 g486(.A (empty), .B (n_18), .C (n_21), .Y
       (n_23));
  sky130_fd_sc_hd__dfrtp_1 \g_rptr_reg[10] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[10]), .Q (g_rptr[10]));
  sky130_fd_sc_hd__nand2_1 g488(.A (n_72), .B (n_73), .Y (n_21));
  sky130_fd_sc_hd__nand2b_1 g489(.A_N (empty), .B (r_en), .Y (n_20));
  sky130_fd_sc_hd__nand2b_1 g490(.A_N (empty), .B (n_73), .Y (n_19));
  sky130_fd_sc_hd__inv_1 g491(.A (n_71), .Y (n_18));
  sky130_fd_sc_hd__sdfstp_1 empty_reg(.SET_B (rrst_n), .CLK (rclk), .D
       (n_16), .SCD (1'b0), .SCE (1'b0), .Q (n_17));
  sky130_fd_sc_hd__nor3_1 g218(.A (n_10), .B (n_11), .C (n_15), .Y
       (n_16));
  sky130_fd_sc_hd__nand4_1 g219(.A (n_14), .B (n_6), .C (n_7), .D
       (n_8), .Y (n_15));
  sky130_fd_sc_hd__a21oi_1 g220(.A1 (g_rptr_next[0]), .A2 (n_5), .B1
       (n_13), .Y (n_14));
  sky130_fd_sc_hd__o221ai_1 g221(.A1 (n_3), .A2 (n_0), .B1
       (g_wptr_sync[4]), .B2 (n_1), .C1 (n_12), .Y (n_13));
  sky130_fd_sc_hd__a21oi_1 g222(.A1 (g_wptr_sync[9]), .A2 (n_4), .B1
       (n_9), .Y (n_12));
  sky130_fd_sc_hd__xor2_1 g223(.A (g_wptr_sync[2]), .B
       (g_rptr_next[2]), .X (n_11));
  sky130_fd_sc_hd__xor2_1 g224(.A (g_wptr_sync[3]), .B
       (g_rptr_next[3]), .X (n_10));
  sky130_fd_sc_hd__mux2i_1 g225(.A0 (n_4), .A1 (g_wptr_sync[9]), .S
       (g_wptr_sync[10]), .Y (n_9));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[4] (.RESET_B (rrst_n), .CLK
       (rclk), .D (n_0), .Q (b_rptr[4]));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[0] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[0]), .Q (n_73));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[3] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[3]), .Q (b_rptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[1] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[1]), .Q (n_72));
  sky130_fd_sc_hd__nand2b_1 g230(.A_N (g_rptr_next[0]), .B
       (g_wptr_sync[0]), .Y (n_8));
  sky130_fd_sc_hd__nand2b_1 g231(.A_N (g_wptr_sync[1]), .B
       (g_rptr_next[1]), .Y (n_7));
  sky130_fd_sc_hd__dfrtp_1 \b_rptr_reg[2] (.RESET_B (rrst_n), .CLK
       (rclk), .D (b_rptr_next[2]), .Q (n_71));
  sky130_fd_sc_hd__nand2b_1 g233(.A_N (g_rptr_next[1]), .B
       (g_wptr_sync[1]), .Y (n_6));
  sky130_fd_sc_hd__inv_1 g234(.A (g_wptr_sync[0]), .Y (n_5));
  sky130_fd_sc_hd__inv_1 g235(.A (b_rptr_next[10]), .Y (n_4));
  sky130_fd_sc_hd__inv_1 g237(.A (g_wptr_sync[4]), .Y (n_3));
  sky130_fd_sc_hd__inv_1 drc_bufs238(.A (n_1), .Y (n_0));
  sky130_fd_sc_hd__inv_1 drc_bufs239(.A (b_rptr_next[4]), .Y (n_1));
  sky130_fd_sc_hd__clkbuf_2 drc(.A (n_17), .X (empty));
endmodule

module synchronizer_WIDTH10_1(clk, rst_n, d_in, d_out);
  input clk, rst_n;
  input [10:0] d_in;
  output [10:0] d_out;
  wire clk, rst_n;
  wire [10:0] d_in;
  wire [10:0] d_out;
  wire [10:0] q1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  assign d_out[5] = 1'b0;
  assign d_out[6] = 1'b0;
  assign d_out[7] = 1'b0;
  assign d_out[8] = 1'b0;
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[0] (.CLK (clk), .D (n_13), .Q
       (d_out[0]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[9] (.CLK (clk), .D (n_12), .Q
       (d_out[9]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[3] (.CLK (clk), .D (n_8), .Q
       (d_out[3]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[2] (.CLK (clk), .D (n_9), .Q
       (d_out[2]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[1] (.CLK (clk), .D (n_10), .Q
       (d_out[1]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[10] (.CLK (clk), .D (n_11), .Q
       (d_out[10]));
  sky130_fd_sc_hd__and2_0 g26(.A (q1[0]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__and2_0 g25(.A (q1[9]), .B (rst_n), .X (n_12));
  sky130_fd_sc_hd__and2_0 g27(.A (q1[10]), .B (rst_n), .X (n_11));
  sky130_fd_sc_hd__and2_0 g28(.A (q1[1]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__and2_0 g29(.A (q1[2]), .B (rst_n), .X (n_9));
  sky130_fd_sc_hd__and2_0 g30(.A (q1[3]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[9] (.CLK (clk), .D (n_6), .Q
       (q1[9]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[10] (.CLK (clk), .D (n_4), .Q
       (q1[10]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[2] (.CLK (clk), .D (n_2), .Q
       (q1[2]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[1] (.CLK (clk), .D (n_3), .Q
       (q1[1]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[3] (.CLK (clk), .D (n_7), .Q
       (q1[3]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[0] (.CLK (clk), .D (n_5), .Q
       (q1[0]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[4] (.CLK (clk), .D (n_1), .Q
       (d_out[4]));
  sky130_fd_sc_hd__and2_0 g45(.A (d_in[3]), .B (rst_n), .X (n_7));
  sky130_fd_sc_hd__and2_1 g39(.A (d_in[9]), .B (rst_n), .X (n_6));
  sky130_fd_sc_hd__and2_0 g41(.A (d_in[0]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__and2_1 g42(.A (d_in[9]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__and2_0 g43(.A (d_in[1]), .B (rst_n), .X (n_3));
  sky130_fd_sc_hd__and2_0 g44(.A (d_in[2]), .B (rst_n), .X (n_2));
  sky130_fd_sc_hd__and2_0 g31(.A (q1[4]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[4] (.CLK (clk), .D (n_0), .Q
       (q1[4]));
  sky130_fd_sc_hd__and2_1 g40(.A (d_in[4]), .B (rst_n), .X (n_0));
endmodule

module synchronizer_WIDTH10(clk, rst_n, d_in, d_out);
  input clk, rst_n;
  input [10:0] d_in;
  output [10:0] d_out;
  wire clk, rst_n;
  wire [10:0] d_in;
  wire [10:0] d_out;
  wire [10:0] q1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  assign d_out[5] = 1'b0;
  assign d_out[6] = 1'b0;
  assign d_out[7] = 1'b0;
  assign d_out[8] = 1'b0;
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[0] (.CLK (clk), .D (n_8), .Q
       (d_out[0]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[9] (.CLK (clk), .D (n_9), .Q
       (d_out[9]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[3] (.CLK (clk), .D (n_10), .Q
       (d_out[3]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[2] (.CLK (clk), .D (n_11), .Q
       (d_out[2]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[1] (.CLK (clk), .D (n_12), .Q
       (d_out[1]));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[10] (.CLK (clk), .D (n_13), .Q
       (d_out[10]));
  sky130_fd_sc_hd__and2_0 g25(.A (q1[10]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__and2_0 g26(.A (q1[1]), .B (rst_n), .X (n_12));
  sky130_fd_sc_hd__and2_0 g27(.A (q1[2]), .B (rst_n), .X (n_11));
  sky130_fd_sc_hd__and2_0 g28(.A (q1[3]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__and2_0 g30(.A (q1[9]), .B (rst_n), .X (n_9));
  sky130_fd_sc_hd__and2_0 g31(.A (q1[0]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[1] (.CLK (clk), .D (n_3), .Q
       (q1[1]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[2] (.CLK (clk), .D (n_5), .Q
       (q1[2]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[3] (.CLK (clk), .D (n_4), .Q
       (q1[3]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[9] (.CLK (clk), .D (n_2), .Q
       (q1[9]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[0] (.CLK (clk), .D (n_7), .Q
       (q1[0]));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[10] (.CLK (clk), .D (n_6), .Q
       (q1[10]));
  sky130_fd_sc_hd__and2_1 g45(.A (d_in[0]), .B (rst_n), .X (n_7));
  sky130_fd_sc_hd__and2_1 g39(.A (d_in[9]), .B (rst_n), .X (n_6));
  sky130_fd_sc_hd__and2_1 g40(.A (d_in[2]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__and2_1 g41(.A (d_in[3]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__and2_1 g43(.A (d_in[1]), .B (rst_n), .X (n_3));
  sky130_fd_sc_hd__and2_1 g44(.A (d_in[9]), .B (rst_n), .X (n_2));
  sky130_fd_sc_hd__dfxtp_1 \d_out_reg[4] (.CLK (clk), .D (n_1), .Q
       (d_out[4]));
  sky130_fd_sc_hd__and2_0 g29(.A (q1[4]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__dfxtp_1 \q1_reg[4] (.CLK (clk), .D (n_0), .Q
       (q1[4]));
  sky130_fd_sc_hd__and2_1 g42(.A (d_in[4]), .B (rst_n), .X (n_0));
endmodule

module wptr_handler_PTR_WIDTH10(wclk, wrst_n, w_en, g_rptr_sync,
     b_wptr, g_wptr, full);
  input wclk, wrst_n, w_en;
  input [10:0] g_rptr_sync;
  output [10:0] b_wptr, g_wptr;
  output full;
  wire wclk, wrst_n, w_en;
  wire [10:0] g_rptr_sync;
  wire [10:0] b_wptr, g_wptr;
  wire full;
  wire [10:0] g_wptr_next;
  wire [10:0] b_wptr_next;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_59, n_64;
  assign g_wptr[4] = 1'b0;
  assign g_wptr[5] = 1'b0;
  assign g_wptr[6] = 1'b0;
  assign g_wptr[7] = 1'b0;
  assign g_wptr[8] = 1'b0;
  assign g_wptr[9] = 1'b0;
  assign b_wptr[5] = 1'b0;
  assign b_wptr[6] = 1'b0;
  assign b_wptr[7] = 1'b0;
  assign b_wptr[8] = 1'b0;
  assign b_wptr[9] = 1'b0;
  assign b_wptr[10] = 1'b0;
  sky130_fd_sc_hd__buf_1 g56(.A (n_59), .X (full));
  sky130_fd_sc_hd__clkbuf_1 g57(.A (n_64), .X (b_wptr[0]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[3] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[3]), .Q (g_wptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[2] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[2]), .Q (g_wptr[2]));
  sky130_fd_sc_hd__o21ai_1 g435(.A1 (n_23), .A2 (b_wptr_next[3]), .B1
       (n_27), .Y (g_wptr_next[2]));
  sky130_fd_sc_hd__o21ai_1 g436(.A1 (b_wptr_next[4]), .A2 (n_25), .B1
       (n_26), .Y (g_wptr_next[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[1] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[1]), .Q (g_wptr[1]));
  sky130_fd_sc_hd__nand2_1 g438(.A (b_wptr_next[3]), .B (n_23), .Y
       (n_27));
  sky130_fd_sc_hd__nand2_1 g439(.A (n_25), .B (b_wptr_next[4]), .Y
       (n_26));
  sky130_fd_sc_hd__o2bb2ai_1 g440(.A1_N (b_wptr_next[1]), .A2_N (n_23),
       .B1 (b_wptr_next[1]), .B2 (n_23), .Y (g_wptr_next[1]));
  sky130_fd_sc_hd__inv_2 g441(.A (b_wptr_next[3]), .Y (n_25));
  sky130_fd_sc_hd__a21o_1 g442(.A1 (n_22), .A2 (b_wptr[3]), .B1 (n_24),
       .X (b_wptr_next[3]));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[0] (.RESET_B (wrst_n), .CLK
       (wclk), .D (g_wptr_next[0]), .Q (g_wptr[0]));
  sky130_fd_sc_hd__nor2_1 g444(.A (b_wptr[3]), .B (n_22), .Y (n_24));
  sky130_fd_sc_hd__inv_2 g445(.A (b_wptr_next[2]), .Y (n_23));
  sky130_fd_sc_hd__a2bb2o_1 g446(.A1_N (b_wptr[4]), .A2_N (n_21), .B1
       (b_wptr[4]), .B2 (n_21), .X (b_wptr_next[4]));
  sky130_fd_sc_hd__xor2_1 g447(.A (b_wptr_next[0]), .B
       (b_wptr_next[1]), .X (g_wptr_next[0]));
  sky130_fd_sc_hd__o2bb2ai_1 g448(.A1_N (b_wptr[2]), .A2_N (n_19), .B1
       (b_wptr[2]), .B2 (n_19), .Y (b_wptr_next[2]));
  sky130_fd_sc_hd__nand2_1 g449(.A (n_20), .B (b_wptr[2]), .Y (n_22));
  sky130_fd_sc_hd__nand2_1 g450(.A (w_en), .B (n_17), .Y (n_21));
  sky130_fd_sc_hd__a21o_1 g451(.A1 (n_16), .A2 (b_wptr[1]), .B1 (n_18),
       .X (b_wptr_next[1]));
  sky130_fd_sc_hd__inv_2 g452(.A (n_19), .Y (n_20));
  sky130_fd_sc_hd__nor2_1 g453(.A (b_wptr[1]), .B (n_16), .Y (n_18));
  sky130_fd_sc_hd__nand2_1 g454(.A (w_en), .B (n_15), .Y (n_19));
  sky130_fd_sc_hd__and3_1 g455(.A (n_15), .B (b_wptr[3]), .C
       (b_wptr[2]), .X (n_17));
  sky130_fd_sc_hd__o2bb2ai_1 g456(.A1_N (n_64), .A2_N (n_14), .B1
       (n_64), .B2 (n_14), .Y (b_wptr_next[0]));
  sky130_fd_sc_hd__nand2_1 g457(.A (w_en), .B (n_13), .Y (n_16));
  sky130_fd_sc_hd__and2_1 g458(.A (n_13), .B (b_wptr[1]), .X (n_15));
  sky130_fd_sc_hd__dfrtp_1 \g_wptr_reg[10] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[10]), .Q (g_wptr[10]));
  sky130_fd_sc_hd__nand2b_1 g460(.A_N (n_59), .B (w_en), .Y (n_14));
  sky130_fd_sc_hd__nor2b_1 g461(.A (n_59), .B_N (n_64), .Y (n_13));
  sky130_fd_sc_hd__dfrtp_1 full_reg(.RESET_B (wrst_n), .CLK (wclk), .D
       (n_12), .Q (n_59));
  sky130_fd_sc_hd__nor3_1 g248(.A (n_0), .B (n_8), .C (n_11), .Y
       (n_12));
  sky130_fd_sc_hd__nand4_1 g249(.A (n_10), .B (n_6), .C (n_4), .D
       (n_5), .Y (n_11));
  sky130_fd_sc_hd__a21oi_1 g250(.A1 (g_wptr_next[0]), .A2 (n_1), .B1
       (n_9), .Y (n_10));
  sky130_fd_sc_hd__o2111ai_1 g251(.A1 (b_wptr_next[10]), .A2
       (g_rptr_sync[10]), .B1 (n_7), .C1 (n_2), .D1 (n_3), .Y (n_9));
  sky130_fd_sc_hd__a2bb2oi_1 g252(.A1_N (g_rptr_sync[2]), .A2_N
       (g_wptr_next[2]), .B1 (g_rptr_sync[2]), .B2 (g_wptr_next[2]), .Y
       (n_8));
  sky130_fd_sc_hd__mux2i_1 g254(.A0 (g_rptr_sync[10]), .A1
       (b_wptr_next[10]), .S (g_rptr_sync[9]), .Y (n_7));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[4] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[4]), .Q (b_wptr[4]));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[0] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[0]), .Q (n_64));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[3] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[3]), .Q (b_wptr[3]));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[1] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[1]), .Q (b_wptr[1]));
  sky130_fd_sc_hd__dfrtp_1 \b_wptr_reg[2] (.RESET_B (wrst_n), .CLK
       (wclk), .D (b_wptr_next[2]), .Q (b_wptr[2]));
  sky130_fd_sc_hd__nand2b_1 g260(.A_N (g_wptr_next[1]), .B
       (g_rptr_sync[1]), .Y (n_6));
  sky130_fd_sc_hd__nand2b_1 g261(.A_N (g_wptr_next[0]), .B
       (g_rptr_sync[0]), .Y (n_5));
  sky130_fd_sc_hd__nand2b_1 g262(.A_N (g_rptr_sync[1]), .B
       (g_wptr_next[1]), .Y (n_4));
  sky130_fd_sc_hd__nand2b_1 g263(.A_N (b_wptr_next[4]), .B
       (g_rptr_sync[4]), .Y (n_3));
  sky130_fd_sc_hd__nand2b_1 g264(.A_N (g_rptr_sync[4]), .B
       (b_wptr_next[4]), .Y (n_2));
  sky130_fd_sc_hd__inv_1 g265(.A (g_rptr_sync[0]), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2(.A (g_rptr_sync[3]), .B (g_wptr_next[3]),
       .X (n_0));
endmodule

module asynchronous_fifo(wclk, wrst_n, rclk, rrst_n, w_en, r_en,
     data_in, data_out, full, empty);
  input wclk, wrst_n, rclk, rrst_n, w_en, r_en;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty;
  wire wclk, wrst_n, rclk, rrst_n, w_en, r_en;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty;
  wire [10:0] b_wptr;
  wire [10:0] b_rptr;
  wire [10:0] g_wptr_sync;
  wire [10:0] g_rptr;
  wire [10:0] g_rptr_sync;
  wire [10:0] g_wptr;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36;
  fifo_mem fifom(wclk, w_en, rclk, r_en, {5'b00000, b_wptr[4:0]},
       {5'b00000, b_rptr[4:0]}, data_in, full, 1'b0, data_out);
  rptr_handler_PTR_WIDTH10 rptr_h(rclk, rrst_n, r_en,
       {g_wptr_sync[10:9], 4'b0000, g_wptr_sync[4:0]}, {b_rptr[10],
       UNCONNECTED11, UNCONNECTED10, UNCONNECTED9, UNCONNECTED8,
       UNCONNECTED7, b_rptr[4:0]}, {g_rptr[10], UNCONNECTED17,
       UNCONNECTED16, UNCONNECTED15, UNCONNECTED14, UNCONNECTED13,
       UNCONNECTED12, g_rptr[3:0]}, empty);
  synchronizer_WIDTH10_1 sync_rptr(wclk, wrst_n, {1'b0, g_rptr[10],
       4'b0000, b_rptr[4], g_rptr[3:0]}, {g_rptr_sync[10:9],
       UNCONNECTED21, UNCONNECTED20, UNCONNECTED19, UNCONNECTED18,
       g_rptr_sync[4:0]});
  synchronizer_WIDTH10 sync_wptr(rclk, rrst_n, {1'b0, g_wptr[10],
       4'b0000, b_wptr[4], g_wptr[3:0]}, {g_wptr_sync[10:9],
       UNCONNECTED25, UNCONNECTED24, UNCONNECTED23, UNCONNECTED22,
       g_wptr_sync[4:0]});
  wptr_handler_PTR_WIDTH10 wptr_h(wclk, wrst_n, w_en,
       {g_rptr_sync[10:9], 4'b0000, g_rptr_sync[4:0]}, {b_wptr[10],
       UNCONNECTED30, UNCONNECTED29, UNCONNECTED28, UNCONNECTED27,
       UNCONNECTED26, b_wptr[4:0]}, {g_wptr[10], UNCONNECTED36,
       UNCONNECTED35, UNCONNECTED34, UNCONNECTED33, UNCONNECTED32,
       UNCONNECTED31, g_wptr[3:0]}, full);
endmodule

